import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import { CartProvider } from "@/context/CartContext";
import { UserProvider } from "@/context/UserContext";
import { ThemeProvider } from "@/context/ThemeContext";
import Script from "next/script";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home Land",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    suppressHydrationWarning
      lang="fa"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <head>
        <Script
        id="theme-script"
        strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
          (function() {
          try{
          const theme = localStorage.getItem("theme");
          if(theme === "dark" || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches) {
          document.documentElement.classList.add("dark")
          }
          } catch (e) {}
          })()`
          }} />
      </head> */}
      <body dir="rtl" className=" min-h-full flex flex-col ">
        <ThemeProvider>
          <UserProvider>
            <CartProvider>
              <main className="w-full flex flex-col items-center px-4 sm:px-6 lg:px-8 ">
                <div className="w-full max-w-7xl">
                  <Header />
                  {children}
                  <Footer/>
      
                </div>
              </main>
            </CartProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
